"""Authored desk scene for the SO-101 cube Pick-and-Place task.

The USD is generated by ``scripts/author_pick_cube_scene.py``. This module
exposes the same ``AssetBaseCfg`` indirection so task configs can
``.replace(prim_path=...)`` without knowing the underlying file layout.
"""

from __future__ import annotations

from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.assets import AssetBaseCfg

# This file lives at src/sim_to_real/assets/scenes/cube_desk.py
# parents[4] = repo root  (cube_desk.py -> scenes -> assets -> sim_to_real -> src -> repo)
_REPO_ROOT: Path = Path(__file__).resolve().parents[4]

ASSETS_ROOT: str = str(_REPO_ROOT / "assets")
SCENES_ROOT: Path = _REPO_ROOT / "assets" / "scenes"

CUBE_DESK_USD_PATH: str = str(SCENES_ROOT / "cube_desk" / "scene.usd")
ROBOT_USD_PATH: str = str(_REPO_ROOT / "assets" / "robots" / "so101_follower.usd")


CUBE_DESK_CFG = AssetBaseCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=CUBE_DESK_USD_PATH,
    ),
)
