"""Authored desk scene for the SO-101 pen Pick-and-Place task.

The USD is generated by ``scripts/author_pick_pen_scene.py``. This module
exposes the same ``AssetBaseCfg`` indirection that leisaac uses (e.g.
``KITCHEN_WITH_ORANGE_CFG``) so task configs can ``.replace(prim_path=...)``
without knowing the underlying file layout.
"""

from __future__ import annotations

from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.assets import AssetBaseCfg

from leisaac.utils.constant import ASSETS_ROOT

SCENES_ROOT = Path(ASSETS_ROOT) / "scenes"

PEN_DESK_USD_PATH: str = str(SCENES_ROOT / "pen_desk" / "scene.usd")


PEN_DESK_CFG = AssetBaseCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=PEN_DESK_USD_PATH,
    ),
)
