joints:
  shoulder_pan:
    id: 1
    drive_mode: 0
    homing_offset: -1579
    range_min: 827
    range_max: 3394
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254
  shoulder_lift:
    id: 2
    drive_mode: 0
    homing_offset: -1618
    range_min: 906
    range_max: 3218
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254
  elbow_flex:
    id: 3
    drive_mode: 0
    homing_offset: 1717
    range_min: 838
    range_max: 3249
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254
  wrist_flex:
    id: 4
    drive_mode: 0
    homing_offset: 1503
    range_min: 683
    range_max: 3166
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254
  wrist_roll:
    id: 5
    drive_mode: 0
    homing_offset: -778
    range_min: 0
    range_max: 4095
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254
  gripper:
    id: 6
    drive_mode: 0
    homing_offset: -1706
    range_min: 1423
    range_max: 3037
    p_coefficient: 16
    i_coefficient: 0
    d_coefficient: 32
    return_delay_time: 0
    acceleration: 254
    max_torque_limit: 500
    protection_current: 250
    overload_torque: 25
